import { SITE } from "@/lib/site";

const baseUrl = SITE.siteUrl;

const paths = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" },
  { path: "/premium", priority: 0.6, changeFrequency: "monthly" },
  { path: "/privacy", priority: 0.6, changeFrequency: "monthly" },
  { path: "/cookie-policy", priority: 0.6, changeFrequency: "monthly" },
  { path: "/affiliate-disclosure", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/testo", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/immagini", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/utility", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/ai", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/word-counter", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/text-case-converter", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/ai-summarizer", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/lorem-ipsum", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/remove-duplicates", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/slug-generator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/markdown-to-html", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/text-diff", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/text-to-speech", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-merger", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-splitter", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-compressor", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-editor", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-rotator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/images-to-pdf", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-to-images", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-page-numbers", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/pdf-reverse", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/image-compressor", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/image-converter", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/image-resizer", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/ocr-extractor", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/image-filters", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/image-rotator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/ascii-art", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/ai-image-generator", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/password-generator", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/password-manager", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/qr-code-generator", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/unit-converter", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/random-generator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/base64-converter", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/url-encoder", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/color-converter", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/uuid-generator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/timer", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/age-calculator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/percentage-calculator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/hash-generator", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/base-converter", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strumenti/ai-chat", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/ai-rewriter", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/ai-translator", priority: 0.8, changeFrequency: "monthly" },
  { path: "/strumenti/ai-email", priority: 0.8, changeFrequency: "monthly" },
] as const;

export default async function sitemap() {
  return paths.map(({ path, priority, changeFrequency }) => ({
    url: `${baseUrl}${path === "/" ? "" : path}`,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }));
}
